<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
<!DOCTYPE html>
<html lang="pt-Br">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Supermercado Recanto</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<?php echo $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'/css/bootstrap.css')?>


<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if IE 7]><link rel="stylesheet" href="css/ie7.css" type="text/css" media="all" /><![endif]-->
<!--[if IE 8]><link rel="stylesheet" href="css/ie8.css" type="text/css" media="all" /><![endif]-->
<!--[if IE ]><link rel="stylesheet" href="css/ie.css" type="text/css" media="all" /><![endif]-->
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
<!-- Le fav and touch icons -->

<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery-1.8.3.min.js"></script>

</head>
<body>
    <div class="container">
        <?php echo $this->layout()->content; ?>	
    </div>
	
</body>
</html>